# Copyright (c) 2022 OpenFaaS Ltd
name: 'Install SSHD for actor'
description: 'Install SSHD for actor'
branding:
  icon: 'arrow-right-circle'
  color: 'gray-dark'
runs:
    using: 'composite'
    steps:
      - name: Install SSHD
        shell: bash
        id: download
        run: |
            sudo systemctl status|grep ssh
            
            sudo apt update && \
            sudo apt install -qqy openssh-server && \
            sudo systemctl enable ssh
            
            if [ -z "$(find /etc/ssh/ -name "ssh_host_*"|xargs echo -n)" ]; then DEBIAN_FRONTEND=noninteractive sudo -E dpkg-reconfigure openssh-server ;  fi
      - name: Disable password auth
        shell: bash
        id: disablepwd
        run: |
          echo "PasswordAuthentication no" | sudo tee -a /etc/ssh/sshd_config
          echo "ChallengeResponseAuthentication no" | sudo tee -a /etc/ssh/sshd_config
          sudo sed -i "s/.*PasswordAuthentication.*/PasswordAuthentication no/g" /etc/ssh/sshd_config
      
          sudo systemctl daemon-reload
          
          sudo systemctl status|grep ssh
          
          sudo systemctl restart ssh --now
      - name: Install actor's keys
        shell: bash
        id: keys
        run: |
          mkdir -p ~/.ssh
          
          curl -s "https://api.github.com/users/$GITHUB_ACTOR/keys" | jq -r '.[].key' > ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys


